### ISSUE TITLE
First Media sekarang menggunakan DPI, DNScrypt sudah tidak bisa digunakan untuk mengakses reddit

### ISSUE THREAD

**Issue by onmyouji** [bebasid/KominFudge#10]
### Apa yang salah?

First Media sekarang menggunakan DPI

### Harusnya apa?

First Media sekarang menggunakan DPI

### Berikan sumber

https://i.imgur.com/qJ3RyuH.png

**Comment by SlashyID** [comment]
Sudah di add ya
