### ISSUE TITLE
Indihome masih belum pakai DPI

### ISSUE THREAD

**Issue by F640** [bebasid/KominFudge#68]
### Informasi apa yang salah atau kadaluwarsa?

Indihome menggunakan DPI

### Informasi yang benar

Indihome masih belum menggunakan DPI (hanya redirect DNS biasa)

### Referensi

![SS traceroute `old.reddit.com` dengan DoT Cloudflare](https://github.com/bebasid/KominFudge/assets/92260436/29b899d8-c045-425f-9c25-c478bf90580e)

### Informasi tambahan

Selama ini saya menggunakan DoT Cloudflare (one.one.one.one) di router untuk bypass blokiran Indihome

**Comment by ryukora** [comment]
Tinggal daerah mana

**Comment by ryukora** [comment]
> ### Informasi apa yang salah atau kadaluwarsa?
> Indihome menggunakan DPI
> 
> ### Informasi yang benar
> Indihome masih belum menggunakan DPI (hanya redirect DNS biasa)
> 
> ### Referensi
> ![SS traceroute old.reddit.com dengan DoT Cloudflare](https://private-user-images.githubusercontent.com/92260436/315921232-29b899d8-c045-425f-9c25-c478bf90580e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc5MDUsIm5iZiI6MTcxMTA5NzYwNSwicGF0aCI6Ii85MjI2MDQzNi8zMTU5MjEyMzItMjliODk5ZDgtYzA0NS00MjVmLTljMjUtYzQ3OGJmOTA1ODBlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjhmYmQyMjQ4YzU0YTM5M2Q1YmVhNDkyNWVmNDIxZjRjNmVhNjY5YWMxYWY0YTcwODBjYTY5OTUzYzI2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sXmZwyfpV5sIfhvClfgNXsI6GqJBiwgGR_PKwyinQw)
> 
> ### Informasi tambahan
> Selama ini saya menggunakan DoT Cloudflare (one.one.one.one) di router untuk bypass blokiran Indihome

Tinggal daerah mana? Jabodetabek sini kena.

**Comment by F640** [comment]
Tinggal di pontianak, kalimantan barat

**Comment by ryukora** [comment]
> Tinggal di pontianak, kalimantan barat
> […](#)
> On March 22, 2024 3:54:01 PM GMT+07:00, Ryukura ***@***.***> wrote: > ### Informasi apa yang salah atau kadaluwarsa? > Indihome menggunakan DPI > > ### Informasi yang benar > Indihome masih belum menggunakan DPI (hanya redirect DNS biasa) > > ### Referensi > ![SS traceroute old.reddit.com dengan DoT Cloudflare](https://private-user-images.githubusercontent.com/92260436/315921232-29b899d8-c045-425f-9c25-c478bf90580e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc5MDUsIm5iZiI6MTcxMTA5NzYwNSwicGF0aCI6Ii85MjI2MDQzNi8zMTU5MjEyMzItMjliODk5ZDgtYzA0NS00MjVmLTljMjUtYzQ3OGJmOTA1ODBlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjhmYmQyMjQ4YzU0YTM5M2Q1YmVhNDkyNWVmNDIxZjRjNmVhNjY5YWMxYWY0YTcwODBjYTY5OTUzYzI2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sXmZwyfpV5sIfhvClfgNXsI6GqJBiwgGR_PKwyinQw) > > ### Informasi tambahan > Selama ini saya menggunakan DoT Cloudflare (one.one.one.one) di router untuk bypass blokiran Indihome Tinggal daerah mana? Jabodetabek sini kena. -- Reply to this email directly or view it on GitHub: [#68 (comment)](https://github.com/bebasid/KominFudge/issues/68#issuecomment-2014637121) You are receiving this because you authored the thread. Message ID: ***@***.***>

Oh. DPI Indihome hanya biasanya di Jabodetabek, di luar daerah itu jarang kena.

**Comment by ryukora** [comment]
@F640 Mohon dikonfirmasikan lagi ya, terimakasih.

> > Tinggal di pontianak, kalimantan barat
> > […](#)
> > On March 22, 2024 3:54:01 PM GMT+07:00, Ryukura _**@**_._**> wrote: > ### Informasi apa yang salah atau kadaluwarsa? > Indihome menggunakan DPI > > ### Informasi yang benar > Indihome masih belum menggunakan DPI (hanya redirect DNS biasa) > > ### Referensi > ![SS traceroute old.reddit.com dengan DoT Cloudflare](https://private-user-images.githubusercontent.com/92260436/315921232-29b899d8-c045-425f-9c25-c478bf90580e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc5MDUsIm5iZiI6MTcxMTA5NzYwNSwicGF0aCI6Ii85MjI2MDQzNi8zMTU5MjEyMzItMjliODk5ZDgtYzA0NS00MjVmLTljMjUtYzQ3OGJmOTA1ODBlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjhmYmQyMjQ4YzU0YTM5M2Q1YmVhNDkyNWVmNDIxZjRjNmVhNjY5YWMxYWY0YTcwODBjYTY5OTUzYzI2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sXmZwyfpV5sIfhvClfgNXsI6GqJBiwgGR_PKwyinQw) > > ### Informasi tambahan > Selama ini saya menggunakan DoT Cloudflare (one.one.one.one) di router untuk bypass blokiran Indihome Tinggal daerah mana? Jabodetabek sini kena. -- Reply to this email directly or view it on GitHub: [#68 (comment)](https://github.com/bebasid/KominFudge/issues/68#issuecomment-2014637121) You are receiving this because you authored the thread. Message ID: _**@**_.**_>
> 
> Oh. DPI Indihome biasanya ada di Jabodetabek, di luar daerah itu jarang kena.

**Comment by merdekaid** [comment]
![image](https://github.com/bebasid/KominFudge/assets/115700386/4fd38cef-cc66-4534-8fef-ff7c1379984d)

Rekan KINI sudah tes di daerah Bogor, masih kena ya

**Comment by ryukora** [comment]
> > Oh. DPI Indihome biasanya ada di Jabodetabek, di luar daerah itu jarang kena.
> 
> Jadi itulah mengapa saya mau beritahukan hal ini

Tetapi provider ini hanya kena di seluruh pulau Jawa. Tidak berarti Indihome tidak memakai DPI

**Comment by F640** [comment]
Jadi kesimpulannya indihome hanya menerapkan DPI di daerah tertentu (untuk saat ini). Terima kasih atas informasinya sih

**Comment by merdekaid** [comment]
Di Pulau Jawa kena semua, kalau diluar Pulau Jawa itu jarang. Mungkin karena middleboxnya diinstall di Pulau Jawa menuju keluar doang

**Comment by F640** [comment]
Iya juga sih. Infrastruktur DPI juga tidak murah apalagi kalau harus handle bandwidth yang besar dari seluruh pengguna indihome di satu daerah. 

Hanya saja baguslah menurut saya jika dpi masih belum diterapkan di seluruh daerah Indo. Amit-amit dpi indihome datang ke daerah saya 😣

**Comment by merdekaid** [comment]
Ya begitu lah, mudah mudahan Presiden 2024 lebih mendukung kebebasan berinternet dengan memilih menteri yang kompeten dan mendukung HAM jadinya DPI nya gak nyebar atau bahkan dilepas

**Comment by MikuAuahDark** [comment]
Kasus sama di daerah Makassar. Indihome tidak/belum menggunakan DPI.

**Comment by merdekaid** [comment]
Kebanyakan di Pulau Jawa, kalau di luar Jawa biasanya antara cuman seluler karena gatewaynya harus muter ke JKT atau bahkan gak kena sama sekali
